name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
tag-prefix: ''
categories:
  - title: '🚀 Features'
    label: 'feat'
  - title: '🐛 Bug Fixes'
    label: 'fix'
  - title: '🧪 Chore'
    label: 'chore'
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
version-resolver:
  branch: main  # Corrected this to be an object
template: |
  ## What's Changed
  $CHANGES

  ### Contributors
  $CONTRIBUTORS
