name: Release

on:
  push:
    branches:
      - main # or whatever branch you want to trigger the release from

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies and standard-version (to handle semantic versioning)
      - name: Install dependencies
        run: npm install

      # Run the semantic versioning command
      - name: Bump version and generate changelog
        id: version
        run: npx standard-version --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

      # Create a release on GitHub
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.new_version }}
          release_name: Release v${{ steps.version.outputs.new_version }}
          body: ${{ steps.version.outputs.release_notes }}
          draft: false
          prerelease: false
