name: Draft Release

on:
  push:
    branches:
      - main

jobs:
  draft-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Release Drafter
      uses: release-drafter/release-drafter@v6
      with:
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Publish Draft Release
      run: |
        RELEASE_ID=$(gh release list --limit 1 --json id --jq '.[0].id')
        if [ -n "$RELEASE_ID" ]; then
          gh release edit $RELEASE_ID --draft=false
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
