name: Release

on:
  push:
    branches:
      - main  # Replace with your main branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci

    - name: Bump version using standard-version
      run: |
        npx standard-version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push version and tags
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git push --follow-tags origin main

    - name: Create draft release with Release Drafter
      uses: release-drafter/release-drafter@v5
      with:
        version: ${{ steps.version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish the release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ${{ steps.version.outputs.release_notes }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
