name: Rebase uat onto production

on:
  push:
    branches:
      - production

jobs:
  rebase:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'uat'
          fetch-depth: 0
          lfs: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "manish.bisht@magnifi.ai"
          git config --local user.name "github-actions[bot]"
      
      - name: Use Node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Semantic Release Packages
        run: yarn global add @semantic-release/commit-analyzer@^11.1.0 @semantic-release/git@^10.0.1 @semantic-release/github@^9.2.6 @semantic-release/release-notes-generator@^12.1.0 semantic-release@^22.0.12

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release

      - name: Rebase onto uat
        run: |
          git fetch origin production
          git lfs fetch origin refs/remotes/origin/production
          git rebase origin/production

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'uat'
          force_with_lease: true