name: Release

on:
  push:
    branches:
      - production

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Semantic Release Packages
        run: yarn add @semantic-release/commit-analyzer@^11.1.0 \
                     @semantic-release/git@^10.0.1 \
                     @semantic-release/github@^9.2.6 \
                     @semantic-release/release-notes-generator@^12.1.0 \
                     semantic-release@^22.0.12 --dev

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
