name: Release

on:
  push:
    branches:
      - production

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write    

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'production'
          fetch-depth: 0
          lfs: true
          token: ${{ secrets.PAT_TOKEN }}                   

      - name: Use Node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Semantic Release Packages
        run: yarn global add @semantic-release/commit-analyzer@^11.1.0 @semantic-release/git@^10.0.1 @semantic-release/github@^9.2.6 @semantic-release/release-notes-generator@^12.1.0 semantic-release@^22.0.12

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: semantic-release