name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'

    - name: Install dependencies
      run: npm ci

    - name: Configure Git
      run: |
        git config --local user.email "riteshpanchal16@gmail.com"
        git config --local user.name "RiteshPanchal16"

    - name: Bump version using standard-version
      id: version
      run: |
        npx standard-version
        TAG=$(git describe --tags --abbrev=0)
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "version=$TAG" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug version
      run: |
        echo "Latest tag: ${{ env.TAG }}"
        echo "Captured version: ${{ env.version }}"

    - name: Push version and tags
      run: |
        git push --follow-tags origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create draft release with Release Drafter
      id: drafter
      uses: release-drafter/release-drafter@v6
      with:
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug draft release
      run: |
        cat .github/release-drafter.yml
        echo "Draft release created. Check Release Drafter configuration."

    - name: Publish the release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG }}
        body: |
          $(cat CHANGELOG.md)  # Use generated changelog file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
