name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'

    - name: Install dependencies
      run: npm ci

    - name: Configure Git
      run: |
        git config --local user.email "riteshpanchal16@gmail.com"
        git config --local user.name "RiteshPanchal16"

    - name: Bump version using standard-version
      id: version
      run: |
        npx standard-version
        TAG=$(git describe --tags --abbrev=0)
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "version=$TAG" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push version and tags
      run: |
        git push --follow-tags origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate release notes
      id: release-notes
      run: |
        npx conventional-changelog-cli -p angular -i CHANGELOG.md -s -r 0
        # Debugging: Print the changelog content to ensure it's correct
        cat CHANGELOG.md
        # Strip any special characters and set the environment variable
        RELEASE_NOTES=$(cat CHANGELOG.md | sed 's/[^a-zA-Z0-9 ]//g')
        echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug release notes
      run: |
        echo "Release notes: ${{ env.RELEASE_NOTES }}"

    - name: Create GitHub Release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG }}
        body: ${{ env.RELEASE_NOTES }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
