jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Log GitHub Token (Masked)
        run: echo "Token starts with: ${GITHUB_TOKEN:0:4}..."
        
      - name: Checkout code
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

      # Bump version based on Conventional Commits
      - name: Bump version and tag
        id: version
        uses: phips28/gh-action-bump-version@v10.0.0
        with:
          tag-prefix: 'v'
          skip-tag: 'false'
          default: 'patch'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

      # Log the first few characters of the GitHub token
      - name: Log GitHub Token (Masked)
        run: echo "Token starts with: ${GITHUB_TOKEN:0:4}..."

      # Generate Release Notes
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          version: ${{ steps.version.outputs.new_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

      # Push CHANGELOG.md and updated version files (optional)
      - name: Commit Changelog and Package files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md package.json
          git commit -m "chore(release): update changelog and package.json to v${{ steps.version.outputs.new_version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
