name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Run release-please action
      - name: release-please-action
        uses: googleapis/release-please-action@v4.1.3
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          full-changelog: true
          manifest-file: .release-please-manifest.json

      # Step 2: Install jq for JSON processing
      - name: Install jq
        run: sudo apt-get install jq

      # Step 3: Wait for the release PR creation
      - name: Wait for PR creation
        id: wait-for-pr
        run: |
          MAX_ATTEMPTS=10
          SLEEP_INTERVAL=30
          COUNTER=0
          PR_NUMBER=""

          while [ $COUNTER -lt $MAX_ATTEMPTS ]; do
            echo "Checking for release PR (Attempt $((COUNTER+1))/$MAX_ATTEMPTS)..."

            # Fetch the PR number related to the release using GitHub API
            PR_NUMBER=$(curl -s -H "Authorization: token ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/pulls | \
                jq -r '.[] | select(.title | test("Prepare release: v")) | .number')

            if [[ -n "$PR_NUMBER" ]]; then
              echo "PR found! The PR number is: $PR_NUMBER"
              break
            else
              echo "PR not found, waiting for $SLEEP_INTERVAL seconds..."
            fi

            COUNTER=$((COUNTER+1))
            sleep $SLEEP_INTERVAL
          done

          if [[ -z "$PR_NUMBER" ]]; then
            echo "No PR found after $MAX_ATTEMPTS attempts, failing the job."
            exit 1
          fi

      # Step 4: Merge the pull request
      - name: Merge the pull request
        run: |
          PR_NUMBER="${{ steps.wait-for-pr.outputs.pr_number }}"
          curl -X PUT -H "Authorization: token ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge \
            -d '{"commit_title":"Merging PR #'"$PR_NUMBER"'", "merge_method":"merge"}'
