name: Release

on:
  push:
    branches:
      - main  # Replace with your main branch
permissions:
  contents: read

jobs:
  release:
    permissions:
      # write permission is required to create a github release
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'

    - name: Install dependencies
      run: npm ci

    - name: Configure Git
      run: |
        git config --local user.email "riteshpanchal16@gmail.com"
        git config --local user.name "RiteshPanchal16"

    - name: Bump version using standard-version
      run: |
        npx standard-version
        TAG=$(git describe --tags --abbrev=0)  # Get the latest tag
        echo "TAG=$TAG" >> $GITHUB_ENV         # Store tag in environment variable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push version and tags
      run: |
        git push --follow-tags origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create draft release with Release Drafter
      uses: release-drafter/release-drafter@v6
      with:
        version: ${{ steps.version.outputs.version }}
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish the release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG }}
        body: |
          ${{ steps.version.outputs.release_notes }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
