name: Release

on:
  push:
    branches:
      - main  # Replace with your main branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'

    - name: Install dependencies
      run: npm ci

    - name: Bump version using standard-version
      run: |
        npx standard-version
      env:
        GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

    - name: Push version and tags
      run: |
        git config --global user.email "riteshpanchal16@gmail.com"
        git config --global user.name "RiteshPanchal16"
        git push --follow-tags origin main

    - name: Create draft release with Release Drafter
      uses: release-drafter/release-drafter@v5
      with:
        version: ${{ steps.version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

    - name: Publish the release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ${{ steps.version.outputs.release_notes }}
      env:
<<<<<<< HEAD
        GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
=======
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD
=======
      # Generate Release Notes
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ steps.version.outputs.new_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

      # Push CHANGELOG.md and updated version files (optional)
      - name: Commit Changelog and Package files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md package.json
          git commit -m "chore(release): update changelog and package.json to v${{ steps.version.outputs.new_version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
>>>>>>> fix: some
>>>>>>> fix: some
=======
>>>>>>> fix: somethign
